spring:
  application:
    name: registry

server:
  port: 8081
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url: http://localhost:${server.port}/eureka/
#
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true
